### ISSUE TITLE
Quick question about HW2 

### ISSUE THREAD

**Issue by agulati18** [mikeizbicki/html_validator#5]
Hey Mike, I hope you're well. I don't have a problem with my code. I wanted to reach out to ask if we were allowed to use the regular expressions library for our homework? Thanks.

**Comment by mikeizbicki** [comment]
Please ask this in the https://github.com/mikeizbicki/cmc-csci046 repo.  Everyone in class is following that repo and not this one, so no one else will see the answer here.
